### ISSUE TITLE
 Community activity page

### ISSUE THREAD

**Issue by italojs** [herbsjs/herbsjs.github.io#109]
following the [Tensorflow community](https://blog.tensorflow.org/) page and [Tensorflow Medium page](https://medium.com/tensorflow), I think we could to have a community session to talk about what our "creators" are doing, it could to be an page to centralize the link of all articles, videos and courses....

My initial idea is to have an card (like tensorflow blog or medium posts) for each content contribution, so when someone click in this card, we redirect the user for the original content.

It's is interesting  to increase herbs SEO because we will have many links in our website.

To post the content link into our website, I was thinking in contact the creators and ask then for send an PR into this reopository with they work.

First link suggestions: 
https://www.youtube.com/watch?v=q7kXCTnpCsA&t=1598s
https://lab.vortx.com.br/aprimorando-os-testes-unitarios-com-herbsjs/
https://dev.to/italojs/saving-time-when-starting-a-project-c9n

**Comment by dalssoft** [comment]
I thought the initial idea was just to have a new section on herbs doc (ex: https://herbsjs.org/docs/contrib)

**Comment by italojs** [comment]
yes, is exactly it

**Comment by jhomarolo** [comment]
Are you thinking of using the docusarus blog structure or just a list of links?

Anyway, I think it's nice to have these contents linked to us.

**Comment by italojsv** [comment]
I think we could to build our own layout to do that

**Comment by italojs** [comment]
what do you think put the label `easy4begginers` @jhomarolo

**Comment by italojs** [comment]
WIP

**Comment by dalssoft** [comment]
👏👏👏
