### ISSUE TITLE
Doc: herbs2knex - adds support to identify entity ids

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsjs.github.io#123]
https://herbsjs.org/docs/glues/Herbs2knex#repository-setup

Web documentation is not reflecting the evolution of the lib: 
https://github.com/herbsjs/herbs2knex/pull/42

![image](https://user-images.githubusercontent.com/209287/163687914-fd438d28-27d6-4d9a-878d-3e2f3d6faecb.png)

**Comment by italojs** [comment]
why do not use the gotu to it? because we have the [ID feature ](https://herbsjs.org/docs/entity/features#id-fields)

**Comment by dalssoft** [comment]
@italojs , this issue is just to improve the documentation in order to reflect the changes that are already in use

**Comment by italojs** [comment]
oh sure, i'm sorry, I got confused with HerbsShelf

**Comment by euduardo** [comment]
I'm working on it.

**Comment by euduardo** [comment]
> @euduardo are you still working on this issue? did you have the change to check my comments on the PR? [#128 (review)](https://github.com/herbsjs/herbsjs.github.io/pull/128#pullrequestreview-1003693953)

Sorry about the long waiting time.
Suggestions applied on the PR #142
