### ISSUE TITLE
Herbarium - Documentation

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsjs.github.io#125]
Create Herbarium documentation on Herbs web site

**Comment by mtperesvx** [comment]
i can fix this issue.

**Comment by italojs** [comment]
https://github.com/herbsjs/herbsjs.github.io/issues/125

**Comment by dalssoft** [comment]
Pls, take into the account this new PR/doc from aloe:
https://github.com/herbsjs/herbarium/pull/5/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
