### ISSUE TITLE
Tutorial v2 - Updated tutorial with the newest Herbs and Herbs CLI features

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsjs.github.io#126]
Since the first version of tutorial a lot of improvements arrived in Herbs libraries and CLI but unfortunately the tutorial didn't keep up with the evolution.

We should review the tutorial in a few areas:
- The CLI can be used more extensively on the development lifecycle (`herbs new`, `herbs update`, `herbs update`, `herbs update`, etc)
- Some workflows have changed with the new CLI versions (Folder structure, Entity creation and update, Repository creation and update, REST and GQL structure and lifecycle, Herbs Shelf, etc)
- Herbarium should be explained conceptually and from an implementation point of view (basic / beginner)
- Concepts
- Images
- Code

**Comment by henrisbq** [comment]
I can do this.

**Comment by fgh-magit** [comment]
I will act too.

**Comment by henrisbq** [comment]
@dalssoft a próxima atualização do herbs-cli vai trazer o novo padrão de testes?

**Comment by dalssoft** [comment]
@henrisbq yes, but we still need doc the spec / aloe lib. If you think it is possible to move with the current state of the lib, that would be great. I can also help you make sense of the lib until we have a full doc.

> Has been launched today

I wouldn't call a launch since it's missing many parts like the docs, but yes, it is there to try and test

**Comment by henrisbq** [comment]
@dalssoft, @jhomarolo  I will update my local version e try these changes.

I thinking implement a TO-DO App throughout the tutorial, with two entities, four usecases and some tests.

do you have any drafts of the new features ?  that I can look at and do some testing, so I can get a better idea of what to add to the tutorial

**Comment by dalssoft** [comment]
> I thinking implement a TO-DO App 

fine!

> with two entities, four usecases and some tests

using herbs CLI, you should create the entities manually, but be able to create the use cases (CRUD) automatically using `herbs update`

>I can get a better idea of what to add to the tutorial

Suggestions:

1. being able to show the workflow above (`herbs new` -> edit/add entities -> `herbs update`) is important
2. being able to show that no code is needed to use repositoties, REST and GraphQL because it will be generated on the fly 
3. being able to show the doc will be generated on the fly with Shelf
4. being able to simulate a change in requirements and demonstrate how would be the workflow (`herbs update` if necessary), but reinforcing that no code was necessary to change the infraestructure

**Comment by henrisbq** [comment]
Just to register the work progress i'm saving here link for repo/branch 
https://github.com/henrisbq/herbsjs.github.io/tree/release/tutorial-v2

**Comment by dalssoft** [comment]
Would be great if we could see it running. I think the best way to achieve that would be for you to create a PR and we can test / run on that branch.

**Comment by henrisbq** [comment]
PR:
https://github.com/herbsjs/herbsjs.github.io/pull/139

**Comment by henrisbq** [comment]
Latest update sent in PR: https://github.com/herbsjs/herbsjs.github.io/pull/139

**Comment by jhomarolo** [comment]
Released in #139
