### ISSUE TITLE
Herbs2gql - adds support to custom error handler on default resolver 

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsjs.github.io#136]
Doc this feature

https://github.com/herbsjs/herbs2gql/pull/40/files

**Comment by VictorTBX** [comment]
Isn't this documented here https://herbsjs.org/docs/glues/herbs2gql#apollo-errors-and-err ?

**Comment by VictorTBX** [comment]
https://github.com/herbsjs/herbsjs.github.io/commit/8f8a8a4fe78c56532d4c4270542e84ed4e6fb8dd
