### ISSUE TITLE
New Mobile Usability issues detected for site herbsjs.org

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsjs.github.io#55]
![image](https://user-images.githubusercontent.com/209287/131395866-89ce57d7-8ff9-4380-b6c3-5b30b4f6618e.png)

**Comment by jhomarolo** [comment]
@dalssoft do you have the list or the report about those issues?

**Comment by dalssoft** [comment]
It seems it's no longer a issue:
![image](https://user-images.githubusercontent.com/209287/147502749-66d21b91-2041-4d27-9191-d128062010c4.png)
