### ISSUE TITLE
Logo image on homepage is pixelated.

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsjs.github.io#63]
![image](https://user-images.githubusercontent.com/209287/135084869-2ebf4046-d708-4807-b091-79d502d74a29.png)

Logo image on homepage is pixelated. Probably happens on large / 4k screens.

Is also applies to icons:

![image](https://user-images.githubusercontent.com/209287/135085227-27a941d2-bb98-4edd-93dd-df3719b14d49.png)

**Comment by jhomarolo** [comment]
I think that changing images from png to svg should solve the problem.
