### ISSUE TITLE
Include social media links

### ISSUE THREAD

**Issue by maikvortx** [herbsjs/herbsjs.github.io#72]
Hello guys,

I noticed that the link to documentation and github is duplicated in the header and buttons on the main page. 

I think we can improve the main page by including the social media links in the website header and keeping the documentation and github link in the main page buttons.

We can also change the name of the github button to Project.

Example:

![image](https://user-images.githubusercontent.com/65735194/136609755-6be78ffd-abb7-47e8-b1f6-b8a5c31b7810.png)

**Comment by maikvortx** [comment]
It's a great ideia @dalssoft !

**Comment by priscilanfs28** [comment]
WIP!
