### ISSUE TITLE
Improve the contribution invitation(brainstorm)

### ISSUE THREAD

**Issue by italojs** [herbsjs/herbsjs.github.io#74]
Our [how to contribute](https://herbsjs.org/docs/introduction/contributing) page isn't useful for a new herbs contributors because it's super simple, when someone that never makes an open source contribution read that, they aren't prepared to contribute into herbs so they just to give up.

We cloud to have a more elaborated contribution page that explains about:
- Contribution invitation video;
- Why/when open a issue;
- How you can receive the herbs rewards;
- We could to bring the contributors list to this page;
- Have the Herbs rewards picture (gift, t-shirt, stickers...);
- Hackertober insignia;

Benchmarks: 
https://reactjs.org/docs/how-to-contribute.html
https://www.dataschool.io/how-to-contribute-on-github/

We could to have an Community page that contains:
- Article and videos about herbs made by the community;
- Social media invitation: e.g. discord 

Inside each page we could to have:
- A video about how the lib/glue is coded and architected.
- We could to start to think about low level documentation.

**Comment by jhomarolo** [comment]
IMHO, since we have almost the same instructions about "how to contribute" to all repositories, we can go further with one general session

**Comment by dalssoft** [comment]
> an ELABORATED specific contribution session into each repository/glue
just if it has a specific requirements. but I don't remember having any repo with that

**Comment by anahelenamagit** [comment]
> IMHO, since we have almost the same instructions about "how to contribute" to all repositories, we can go further with one general session

I agree... It's easier to reference it in other projects and easier to mantain. In this unique CONTRIBUTING.md file we could add gifs and/or videos

I'd suggest we add in the [herbs](https://github.com/herbsjs/herbs) repo

**Comment by anahelenasilva** [comment]
> IMHO, since we have almost the same instructions about "how to contribute" to all repositories, we can go further with one general session

I agree... It's easier to reference it in other projects and easier to mantain. In this unique CONTRIBUTING.md file we could add gifs and/or videos

I'd suggest we add in the [herbs](https://github.com/herbsjs/herbs) repo

**Comment by italojsv** [comment]
I get it and I will implement it.
