### ISSUE TITLE
Documentation with wrong function name

### ISSUE THREAD

**Issue by endersoncosta** [herbsjs/herbsjs.github.io#75]
The err is `Err.invalidArguments` but today we have documented as `Err.invalidArgument`

Wrong doc
https://github.com/herbsjs/herbsjs.github.io/blob/master/docs/usecase/result.md

Buchu doc with the right example
https://github.com/herbsjs/buchu

**Comment by Diogooliveira-tech-Vortx** [comment]
Acting on this issue

**Comment by jhomarolo** [comment]
@Diogooliveira-tech-Vortx this issue is already closed.
